#!/usr/bin/env python3
"""
Calculate safety-margin metrics from safety_margin_metrics.npz.

Reported metrics:
  - Episode-wise minimum TTC for:
      * current-lane front vehicle
      * target-lane front vehicle
      * target-lane rear vehicle
    summarized as median [Q25, Q75] over finite episode minima.

  - Proportion of simulation steps for which the minimum TTC across the
    three interaction partners is below a configurable critical threshold.

  - Accepted front and rear merge gaps at merge initiation,
    summarized as median [Q25, Q75] over successful merges.

Usage:
    python calculate_safety_margin_metrics.py safety_margin_metrics.npz
    python calculate_safety_margin_metrics.py safety_margin_metrics.npz --ttc-threshold 1.5
"""

import argparse
import numpy as np


def parse_args():
    parser = argparse.ArgumentParser(
        description="Calculate TTC and accepted-gap safety metrics."
    )
    parser.add_argument(
        "npz_file",
        type=str,
        help="Path to safety_margin_metrics.npz generated by the evaluation script.",
    )
    parser.add_argument(
        "--ttc-threshold",
        type=float,
        default=1.5,
        help="Critical TTC threshold in seconds (default: 1.5 s).",
    )
    return parser.parse_args()


def finite_values(values):
    """Return only finite values, excluding NaN and +/-inf."""
    values = np.asarray(values, dtype=float)
    return values[np.isfinite(values)]


def median_iqr(values):
    """Return median, Q25, Q75, and number of finite samples."""
    values = finite_values(values)
    if values.size == 0:
        return np.nan, np.nan, np.nan, 0

    q25, median, q75 = np.percentile(values, [25, 50, 75])
    return median, q25, q75, values.size


def format_median_iqr(median, q25, q75):
    if not np.all(np.isfinite([median, q25, q75])):
        return "n/a"
    return f"{median:.3f} [{q25:.3f}, {q75:.3f}]"


def require_keys(data, keys):
    missing = [key for key in keys if key not in data]
    if missing:
        raise KeyError(
            "The NPZ file is missing the following required keys: "
            + ", ".join(missing)
        )


def main():
    args = parse_args()
    data = np.load(args.npz_file)

    required_keys = [
        "ttc_current_front",
        "ttc_target_front",
        "ttc_target_rear",
        "episode_min_ttc_current_front",
        "episode_min_ttc_target_front",
        "episode_min_ttc_target_rear",
        "accepted_merge_gap_front",
        "accepted_merge_gap_rear",
    ]
    require_keys(data, required_keys)

    # ------------------------------------------------------------------
    # 1) Episode-wise minimum TTC, summarized across episodes
    # ------------------------------------------------------------------
    ttc_cf = median_iqr(data["episode_min_ttc_current_front"])
    ttc_tf = median_iqr(data["episode_min_ttc_target_front"])
    ttc_tr = median_iqr(data["episode_min_ttc_target_rear"])

    # ------------------------------------------------------------------
    # 2) Proportion of steps below the critical TTC threshold
    #
    # At each simulation step, use the most critical TTC among:
    # current front, target front, and target rear.
    #
    # np.inf naturally represents "no closing conflict" and therefore does
    # not count as a critical step.
    # ------------------------------------------------------------------
    raw_cf = np.asarray(data["ttc_current_front"], dtype=float)
    raw_tf = np.asarray(data["ttc_target_front"], dtype=float)
    raw_tr = np.asarray(data["ttc_target_rear"], dtype=float)

    if not (raw_cf.shape == raw_tf.shape == raw_tr.shape):
        raise ValueError(
            "The three raw TTC arrays must have identical shapes because "
            "they are expected to contain one value per simulation step."
        )

    stepwise_min_ttc = np.minimum.reduce([raw_cf, raw_tf, raw_tr])

    # NaN should not occur under the current environment convention, but
    # exclude such steps defensively if they do.
    valid_steps = ~np.isnan(stepwise_min_ttc)
    if np.any(valid_steps):
        below_threshold = stepwise_min_ttc[valid_steps] < args.ttc_threshold
        critical_step_fraction = float(np.mean(below_threshold))
        critical_step_percent = 100.0 * critical_step_fraction
    else:
        critical_step_fraction = np.nan
        critical_step_percent = np.nan

    # Optional diagnostic: threshold rate for each interaction separately.
    per_type_critical_percent = {}
    for name, values in [
        ("Current front", raw_cf),
        ("Target front", raw_tf),
        ("Target rear", raw_tr),
    ]:
        valid = ~np.isnan(values)
        if np.any(valid):
            per_type_critical_percent[name] = (
                100.0 * np.mean(values[valid] < args.ttc_threshold)
            )
        else:
            per_type_critical_percent[name] = np.nan

    # ------------------------------------------------------------------
    # 3) Accepted merge gaps at merge initiation
    #
    # The evaluation script stores NaN for episodes without a successfully
    # completed merge, so finite values correspond to accepted merge gaps
    # that should be included in the table.
    # ------------------------------------------------------------------
    front_gap = median_iqr(data["accepted_merge_gap_front"])
    rear_gap = median_iqr(data["accepted_merge_gap_rear"])

    # ------------------------------------------------------------------
    # Print results
    # ------------------------------------------------------------------
    print("\nSafety-margin metrics")
    print("=====================")

    print("\nEpisode-wise minimum TTC, median [Q25, Q75]:")
    print(
        f"  Current-lane front : {format_median_iqr(*ttc_cf[:3])} s "
        f"(n={ttc_cf[3]} finite episodes)"
    )
    print(
        f"  Target-lane front  : {format_median_iqr(*ttc_tf[:3])} s "
        f"(n={ttc_tf[3]} finite episodes)"
    )
    print(
        f"  Target-lane rear   : {format_median_iqr(*ttc_tr[:3])} s "
        f"(n={ttc_tr[3]} finite episodes)"
    )

    print(
        f"\nSteps with minimum TTC < {args.ttc_threshold:.2f} s: "
        f"{critical_step_percent:.3f}%"
    )

    print("\nPer-interaction threshold rates (diagnostic):")
    for name, percentage in per_type_critical_percent.items():
        print(f"  {name:<18}: {percentage:.3f}%")

    print("\nAccepted merge gap at merge initiation, median [Q25, Q75]:")
    print(
        f"  Front gap : {format_median_iqr(*front_gap[:3])} m "
        f"(n={front_gap[3]} successful merges)"
    )
    print(
        f"  Rear gap  : {format_median_iqr(*rear_gap[:3])} m "
        f"(n={rear_gap[3]} successful merges)"
    )

    # Optional merge rate if the archive contains the successful_merge flag.
    if "successful_merge" in data:
        successful_merge = np.asarray(data["successful_merge"], dtype=bool)
        if successful_merge.size > 0:
            merge_rate = float(np.mean(successful_merge))
            print(f"\nMerge rate: {merge_rate:.3f}")

    # A compact row that can be copied into the LaTeX table.
    print("\nLaTeX-ready safety-margin cells:")
    print(
        " & ".join(
            [
                format_median_iqr(*ttc_cf[:3]),
                format_median_iqr(*ttc_tf[:3]),
                format_median_iqr(*ttc_tr[:3]),
                f"{critical_step_percent:.3f}",
                format_median_iqr(*front_gap[:3]),
                format_median_iqr(*rear_gap[:3]),
            ]
        )
    )


if __name__ == "__main__":
    main()
